In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
!git clone "https://github.com/Viswapriyacse/Ex.No.3.git"


Cloning into 'Ex.No.3'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.


In [3]:
tf.__version__
'2.8.2'

'2.8.2'

In [4]:
dataset = pd.read_csv('/content/Ex.No.3/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x[:1,:])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [8]:
print(x[:1,:])


[[619 'France' 0 42 2 0.0 1 1 1 101348.88]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [10]:
print(x[:1,:])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5211 - accuracy: 0.7906
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4651 - accuracy: 0.8035
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4489 - accuracy: 0.8071
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4403 - accuracy: 0.8089
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4343 - accuracy: 0.8075
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4300 - accuracy: 0.8085
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4261 - accuracy: 0.8120
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8124
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.8144
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4200 - accura

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1524   71]
 [ 203  202]]


0.863

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]
